workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    PetStore-OAS:
        inputs:
            - location: ./openapi/petstore.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/nick-test/pet-store-oas
targets:
    pet-store:
        target: typescript
        source: PetStore-OAS
        output: ./sdks/typescript
